# 1 引言

### 1.1 Scipy 印象

- `scipy` 包含许多针对科学计算中常规问题的专用工具箱
- `scipy` 的子模块针对各种应用，如插值、积分、优化、图像处理、统计分析、特殊函数等

In [2]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

#### 如果要用到 Matplotlib 功能......

In [ ]:
%matplotlib inline

### 1.2 Scipy 要点

- 高效率

    - 它是 Python 环境下，科学计算的核心程序包
    - 依托 Numpy 数组的支撑，能与之共同高效工作
    

- 同类的著名标准科学计算库

    - GSL (GNU Scientific Library for C and C++)
    - Matlab 工具箱
    

- 代码可靠性

    - 经过严格测试与优化
    - 计算结果可靠

### 1.3 Scipy 的子模块构成

Scipy 是由针对特定任务的子模块构成的，子模块名称及其功能如下表所示

<table border="1" class="docutils">
<colgroup>
<col width="32%">
<col width="68%">
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/cluster.html#module-scipy.cluster" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.cluster</span></tt></a></td>
<td>聚类分析子模块：向量化计算/K平均算法</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/constants.html#module-scipy.constants" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.constants</span></tt></a></td>
<td>物理和数学常量子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/fftpack.html#module-scipy.fftpack" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.fftpack</span></tt></a></td>
<td>快速傅里叶变换子模块</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/integrate.html#module-scipy.integrate" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.integrate</span></tt></a></td>
<td>积分求解子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/interpolate.html#module-scipy.interpolate" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.interpolate</span></tt></a></td>
<td>插值分析子模块</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/io.html#module-scipy.io" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.io</span></tt></a></td>
<td>数据 IO 子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.linalg</span></tt></a></td>
<td>线性代数分析子模块</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/ndimage.html#module-scipy.ndimage" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.ndimage</span></tt></a></td>
<td>图像处理子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/odr.html#module-scipy.odr" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.odr</span></tt></a></td>
<td>正交距离回归分析子模块</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/optimize.html#module-scipy.optimize" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.optimize</span></tt></a></td>
<td>优化子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/signal.html#module-scipy.signal" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.signal</span></tt></a></td>
<td>信号处理子模块</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/sparse.html#module-scipy.sparse" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.sparse</span></tt></a></td>
<td>稀疏矩阵分析子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/spatial.html#module-scipy.spatial" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.spatial</span></tt></a></td>
<td>空间数据结构和算法子模块</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/special.html#module-scipy.special" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.special</span></tt></a></td>
<td>特殊函数子模块</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/stats.html#module-scipy.stats" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.stats</span></tt></a></td>
<td>统计分析子模块</td>
</tr>
</tbody>
</table>

### 1.4 依赖关系

- 所有子模块均依赖于 [numpy](http://docs.scipy.org/doc/numpy/reference/index.html#numpy)
- 子模块之间彼此独立

### 1.5 导入子模块的方式

```python
import scipy.sub_module as short_name
```

#### 例如

In [4]:
from scipy import stats  # 本行代码 导入统计分析子模块，导入其它的子模块类似

In [3]:
from scipy import linalg, optimize # 导入线性代数、优化子模块

### 1.6 函数说明

- 由于历史方面的原因，在 `scipy` 主命名空间中的绝大多数函数，其实就是 numpy 函数（试试 `scipy.cos`，其实是 `np.cos`) 
- 因此，通常可以省略导入命令 `import scipy`

### 1.7 基本函数

#### 使用 Scipy 某个子模块下的函数语法

```python
>>> from scipy import some_module
>>> some_module.some_function()
```

### 1.8 如何获得帮助

- 在线文档
- Help 命令
- IPython 环境下的 ? 查询功能
- **numpy.info 函数**

#### 例如，查询优化子模块下 fmin 函数

In [ ]:
np.info(optimize.fmin)

# 2 文件输入/输出子模块 —— scipy.io

### 2.1 Matlab 文件：载入和保存

- 与 Matlab 进行数据交换的方式
- ones 命令使用上的细微差别

    - Matlab 用法
    ```matlab
    a = ones(3)
    ```
    - Numpy 用法
    ```python
    a = ones((3, 3))
    ```

In [ ]:
from scipy import io as spio

a = np.ones((3, 3))                                      # 3 $\times 3$ 矩阵
spio.savemat('file.mat', {'a': a})                       # 函数 savemat 以字典方式保存数据到文件 file.mat
data = spio.loadmat('file.mat', struct_as_record=True)   # 加载数据文件 file.mat
data['a']                                                # 字典方式访问 关键字 'a' 对应的数据

### 2.2 图象文件：读图象

In [ ]:
from scipy import misc
misc.imread('face.png')

#### 注意警告提示 —— 1.2.0 版本会有语法变化

```
DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
```

In [ ]:
# 查看版本号

import scipy as sp
sp.__version__

In [ ]:
# 修改命令用法

import imageio
imageio.imread('face.png')

In [ ]:
# Matplotlib 子模块下的用法

import matplotlib.pyplot as plt
plt.imread('face.png')

### 2.3 其它参考内容

-  加载文本文件命令
    - [numpy.loadtxt()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html#numpy.loadtxt)
    - [numpy.savetxt()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html#numpy.savetxt)
    

- 智能加载文本/csv文件
    - [numpy.genfromtxt()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt)
    - numpy.recfromcsv()
    
    
- 加载二进制文件 —— 快速有效，但仅适用于 numpy
    - [numpy.save()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html#numpy.save)
    - [numpy.load()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html#numpy.load)

# 3 特殊函数子模块 —— [scipy.special](http://docs.scipy.org/doc/scipy/reference/special.html#scipy.special)

### 3.1 简要说明

- 所有特殊函数都是超越函数
- [scipy.special](http://docs.scipy.org/doc/scipy/reference/special.html#scipy.special) 模块的文档字符串对特殊函数的介绍很详细
- 有关特殊函数的专著（略）

### 3.2 常用的特殊函数

- 贝塞尔函数：       `scipy.special.jn()`  (第n个整型顺序的贝塞尔函数)
- 椭圆函数：        `scipy.special.ellipj()`  (Jacobian椭圆函数, ...)
- $\Gamma$ 函数：     `scipy.special.gamma()`
- $\Gamma$ 对数函数：  `scipy.special.gammaln()` 
- Erf 函数：        `scipy.special.erf()`

### 3.3 贝塞尔函数（实数阶 $\alpha$）

#### 概念

贝塞尔函数（数学上的一类特殊函数的总称）是如下贝塞尔方程

$$x^2\dfrac{d^2 y}{d x^2} + x \dfrac{d y}{d x} + \left(x^2 - \alpha^2\right)y = 0$$

的解函数，其中

- 参数 $\alpha$ 称为相应贝塞尔函数的阶数
- 解函数称为 $\alpha$ 阶贝塞尔函数，记为 $J_{\alpha}(x)$

#### 特性

- 贝塞尔方程的解无法用**初等函数的有限形式**来表示
- 贝塞尔函数在波动问题以及各种涉及有势场的问题中占有非常重要的地位


#### 广泛应用

- 在圆柱形波导中的电磁波传播问题
- 圆柱体中的热传导问题
- 圆形（或环形）薄膜的振动模态分析问题


#### 分类

- 第一类贝塞尔函数
- 第二类贝塞尔函数（诺依曼函数）
- 汉克尔(Hankel)函数
- 黎卡提-贝塞尔函数

#### 第一类贝塞尔函数

$$J_{\alpha}(x) = \sum_{m=0}^{\infty}\dfrac{(-1)^m}{m!\Gamma(m+\alpha+1)}\left(\dfrac{x}{2}\right)^{2m+\alpha}$$

#### 第二类贝塞尔函数（诺依曼函数）

$$Y_{\alpha}(x) = \dfrac{J_{\alpha}(x)\cos(\alpha\pi)-J_{-\alpha}(x)}{\sin(\alpha\pi)}$$

```第二类贝塞尔函数``` 比第一类更为常用，它们是贝塞尔方程的另一类解，又被称为诺依曼函数。

#### Hankel(汉克尔)函数

贝塞尔方程的另外一对重要的线性无关解称为```赫尔曼·汉克尔，汉克尔函数```，分别定义为

$$H_{\alpha}^{(1)}(x)=\dfrac{J_{-\alpha}(x)-e^{-\alpha\pi i}J_{\alpha}(x)}{i\sin(\alpha\pi)}$$
$$H_{\alpha}^{(2)}(x)=\dfrac{J_{-\alpha}(x)-e^{\alpha\pi i}J_{\alpha}(x)}{-i\sin(\alpha\pi)}$$

#### 黎卡提-贝塞尔函数 (Riccati-Bessel functions)

黎卡提-贝塞尔函数（Riccati-Bessel functions）和球贝塞尔函数比较类似。

$$S_n(x)=xj_n(x)=\sqrt{\pi x/2}\,\,J_{n+1/2}(x)$$

$$C_n(x)=-xy_n(x)=-\sqrt{\pi x/2}\,\,Y_{n+1/2}(x)$$

$$\zeta_n(x)=xh_n^{(2)}(x)=\sqrt{\pi x/2}\,\,H_{n+1/2}^{(2)}(x)=S_n(x)+iC_n(x)$$

该函数满足方程

$$x^2\dfrac{d^2y}{dx^2}+\left[x^2-n(n+1)\right]y=0$$

#### 一个实例

- 紧绷的圆型薄皮鼓面在中心受到敲击后的二阶振动振型，其振幅沿半径方向上的分布可用贝塞尔函数表示
- 实际生活中受敲击的鼓面的振动是各阶类似振动形态的叠加

In [ ]:
from scipy import special

# 函数
def drumhead_height(n, k, distance, angle, t):
    kth_zero = special.jn_zeros(n, k)[-1]
    return np.cos(t) * np.cos(n*angle) * special.jn(n, distance*kth_zero)

theta = np.r_[0:2*np.pi:50j]       # 极角
radius = np.r_[0:1:50j]            # 半径

# 三维坐标
x = np.array([r * np.cos(theta) for r in radius])
y = np.array([r * np.sin(theta) for r in radius])
z = np.array([drumhead_height(1, 1, r, theta, 0.5) for r in radius])

In [ ]:
# 画图

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

fig = plt.figure()
ax = Axes3D(fig)

ax.plot_surface(x, y, z, rstride=1, cstride=1, cmap=cm.jet)

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

plt.show()

### 3.4 Cython 关于特殊函数的绑定

Scipy 提供了特殊函数的 Cython 绑定，下例演示了如何使用

```python
cimport scipy.special.cython_special as csc

cdef:
	double x = 1
	double complex z = 1 + 1j
	double si, ci, rgam
	double complex cgam

rgam = csc.gamma(x)
print(rgam)
cgam = csc.gamma(z)
print(cgam)
csc.sici(x, &si, &ci)
print(si, ci)
```

# 4 线性代数分析子模块 —— [scipy.linalg](http://docs.scipy.org/doc/scipy/reference/linalg.html#scipy.linalg)

- 标准的线性代数分析功能实现 [scipy.linalg](http://docs.scipy.org/doc/scipy/reference/linalg.html#scipy.linalg)
- 底层算法库
    - [BLAS](http://www.netlib.org/blas/index.html)
    - [LAPACK](http://www.netlib.org/lapack/index.html)
    - [ATLAS](http://www.netlib.org/atlas/index.html)

### 4.1 scipy.linalg 比较 numpy.linalg

- scipy.linalg 是 numpy.linalg 的超集

    - scipy.linalg 包含了全部的 numpy.linalg 函数
    - scipy.linalg 还包含一些 numpy.linalg 没有的先进函数
    

- scipy.linalg 比 numpy.linalg 更快

    - scipy.linalg 总是获得 BLAS 和 LAPACK 的编译支持
    - numpy.linalg 可选获得 BLAS 和 LAPACK 的编译支持

### 建议

#### 尽量选择 scipy.linalg，而不是 numpy.linalg

### 4.2 矩阵 numpy.matrix 与 2D 数组 numpy.ndarray 相比

- 在矩阵操作方面，numpy.matrix 相比 numpy.ndarray 有更多可靠的接口
- 矩阵运算符方面，numpy.matrix 支持
    - 乘法 *
    - 求逆 I
    - 转置 T

In [ ]:
A = np.mat('[1 2;3 4]')
A

In [ ]:
A.I

In [ ]:
b = np.mat('[5 6]')
b

In [ ]:
b.T

In [ ]:
A*b.T

- 仍然不鼓励使用 numpy.matrix 类型，主要原因是它和 2D numpy.ndarray 合作不好，容易混淆。

### 4.3 求逆矩阵

- [scipy.linalg.inv()](http://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv) 

设有 $3\times 3$ 矩阵

$$
A=
\left[
\begin{array}{ccc}
1 & 3 & 5 \\
2 & 5 & 1 \\
2 & 3 & 8
\end{array}
\right]
$$

其逆矩阵为

$$
A^{-1}=\dfrac{1}{25}
\left[
\begin{array}{rrr}
-37 & 9 & 22 \\
14 & 2 & -9 \\
4 & -3 & 1
\end{array}
\right]
=
\left[
\begin{array}{rrr}
-1.48 & 0.36 & 0.88 \\
0.56 & 0.08 & -0.36 \\
0.16 & -0.12 & 0.04
\end{array}
\right]
$$

Scipy 子模块求解代码如下

In [ ]:
import numpy as np
from scipy import linalg
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

In [ ]:
linalg.inv(A)

In [ ]:
A.dot(linalg.inv(A)) # 检查结果

#### 再看一个 $2\times 2$ 矩阵求逆

In [ ]:
A = np.array([[1, 2],[3, 4]])
A

In [ ]:
linalg.inv(A)

In [ ]:
A.dot(linalg.inv(A))

In [ ]:
np.allclose(A.dot(linalg.inv(A)), np.eye(2)) # 检查求逆运算结果

#### np.allclose 函数介绍

```np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)```

- 功能：逐元素比较两个数组，如果每对元素按一定容差相等，则返回真。
- 参见：isclose, all, any, equal

####  奇异矩阵（行列式为0）求逆

- 将抛出 `LinAlgError`

In [ ]:
arr = np.array([[3, 2],
                 [6, 4]])
linalg.inv(arr)

### 4.4 矩阵矢量乘积

In [ ]:
b = np.array([[5,6]]) # 2 维数组
b

In [ ]:
b.T # 转置

In [ ]:
A*b # 不是矩阵乘矢量，而是广播

In [ ]:
A.dot(b.T) # 矩阵乘矢量

### 4.5 解线性代数方程组

考虑如下方程组

$$
\left\{
\begin{array}{rcl}
x+3y+5z & = & 10\\
2x+5y+z & = & 8 \\
2x+3y+8z & = & 3
\end{array}
\right.
$$

可求得解为

$$
\left[
\begin{array}{c}
x\\
y\\
z
\end{array}
\right]
=
\dfrac{1}{25}\left[
\begin{array}{r}
-232\\
129\\
19
\end{array}
\right]
=
\left[
\begin{array}{r}
-9.28\\
5.16\\
0.76
\end{array}
\right]
$$


In [5]:
A = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])
A


array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [6]:
b = np.array([[10], [8], [3]])
b

array([[10],
       [ 8],
       [ 3]])

In [ ]:
linalg.inv(A).dot(b) # 慢

In [ ]:
A.dot(linalg.inv(A).dot(b)) - b # 检查

In [7]:
np.linalg.solve(A, b) # 快

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [8]:
A.dot(np.linalg.solve(A, b)) - b # 检查

array([[ 0.00000000e+00],
       [-1.77635684e-15],
       [-1.77635684e-15]])

### 4.6 计算行列式

#### 递归求解

$$
\left|A\right|=\sum_{i,j}{(-1)^{i+j}a_{ij}M_{ij}}
$$


#### 示例

设有 $3\times 3$ 矩阵

$$
A=
\left[
\begin{array}{ccc}
1 & 3 & 5 \\
2 & 5 & 1 \\
2 & 3 & 8
\end{array}
\right]
$$

其行列式为

$$
\left|A\right|=-25
$$

求解代码如下

In [ ]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

In [ ]:
linalg.det(A)

#### 再来一个例子

In [ ]:
A = np.array([[1,2],[3,4]])
A

In [ ]:
linalg.det(A)

### 4.7 计算范数

Scipy 可计算矩阵和矢量的多个种类的范数

#### 矢量范数 (缺省 2 阶)

$$
\|x\|
=
\left\{
\begin{array}{cl}
\max|x_i|, & ord=\infty\\
\min|x_i|, & ord=-\infty\\
\left(\sum_i{|x_i|^{ord}}
\right)^{\frac{1}{ord}}, & |ord| < \infty
\end{array}
\right.
$$

#### 矩阵范数 (缺省 2 阶)

$$
\|A\|
=
\left\{
\begin{array}{cl}
\max_{i}\sum_{j}|a_{ij}|, & ord=\infty\\
\min_{i}\sum_{j}|a_{ij}|, & ord=-\infty\\
\max_{j}\sum_{i}|a_{ij}|, & ord=1\\
\min_{j}\sum_{i}|a_{ij}|, & ord=-1\\
\max\sigma_i,& ord=2\\
\min\sigma_i,& ord=-2\\
\sqrt{trace\left(A^HA\right)}, & ord='fro'
\end{array}
\right.
$$

这里，$\sigma_i$ 是矩阵 $A$ 的奇异值。

#### 例如


In [ ]:
A=np.array([[1,2],[3,4]])
A

In [ ]:
linalg.norm(A)

In [ ]:
linalg.norm(A,'fro') # frobenius 范数是缺省？

In [ ]:
linalg.norm(A,1) # L1 范数

In [ ]:
linalg.norm(A,-1)

In [ ]:
linalg.norm(A,np.inf) # L 无穷范数

### 4.8 求解线性最小二乘问题

- 线性最小二乘问题用于拟合数据
- 数据 $y_i$ 依赖于数据 $x_i$，待拟合函数模型为

### $$
y_i = \sum_j{c_j f_j(x_i) + \varepsilon_i}
$$

#### 其中
- $c_i$ 为待求系数
- $f_j(x)$ 为已知函数
- $\varepsilon_i$ 为随机噪声

#### 最小二乘策略

- 寻找系数 $c_i$
- 以使如下目标泛函取最小值

### $$
J(c) = \Sigma_{i}{\left|y_i- \Sigma_j{c_j f_j(x_i)}\right|^2}
$$


#### 结果

记 $a_{ij}=f_j(x_i)$ 为矩阵 $A$ 的元素，可求得

$$c=(A^HA)^{-1}A^Hy$$

其中，$(A^HA)^{-1}A^H$ 称为矩阵 $A$ 的广义逆。

#### 示例

- 给出一组 $x_i=0.1i,\quad i=1,2,\cdots, 10$
- $y_i = c_1e^{-x_i}+c_2x_i + \varepsilon_i$，这里 $\varepsilon_i$ 为噪声
- $c_1=5,\quad c_2=4$

利用最小二乘法求出系数 $c_1$ 和 $c_2$

In [ ]:
# 生成数据
c1, c2 = 5.0, 2.0
i = np.r_[1:11]
xi = 0.1*i
yi = c1*np.exp(-xi) + c2*xi # 无噪声
zi = yi + 0.05 * np.max(yi) * np.random.randn(len(yi)) # 叠加噪声

In [ ]:
# 最小二乘求解
A = np.c_[np.exp(-xi)[:, np.newaxis], xi[:, np.newaxis]]
c, resid, rank, sigma = linalg.lstsq(A, zi)

print("c1 = {0}, c2={1}".format(c[0],c[1]))

In [ ]:
# 利用所求系数画曲线图，先生成坐标数组

xi2 = np.r_[0.1:1.0:100j]
yi2 = c[0]*np.exp(-xi2) + c[1]*xi2

In [ ]:
# 资源设置

mpl.rcParams['font.sans-serif'] = ['SimHei'];
mpl.rcParams['axes.unicode_minus'] = False

In [ ]:
# 数据散点、拟合曲线图

plt.plot(xi,zi,'x', xi2,yi2)
plt.axis([0,1.1,3.0,5.5])
plt.xlabel('$x_i$')
plt.title('采用 linalg.lstsq 进行数据拟合')
plt.show()

### 4.9 求广义逆问题

- 两个函数可用来求广义逆

    - linalg.pinv —— 使用最小二乘法
    - linalg.pinv2 —— 使用奇异值分解法
    
设 $A$ 为 $M\times N$ 矩阵，如果 $M>N$，广义逆就是

$$A^{\dagger}=(A^HA)^{-1}A^H$$

如果 $M<N$，广义逆就是

$$A^{\sharp}=A^H(AA^H)^{-1}$$

如果 $M=N$，则

$$A^{\dagger}=A^\sharp=A^{-1}$$

In [ ]:
A = np.array([[1,3],[2,5],[2,3]]) # M=3, N=2
A

In [ ]:
A_dagger=(linalg.inv(A.T.dot(A))).dot(A.T)
A_dagger

In [ ]:
A_dagger.dot(A)

#### 调用函数 linalg.pinv

In [ ]:
A_dagger_1=linalg.pinv(A)
A_dagger_1

#### 调用函数 linalg.pinv2

In [ ]:
A_dagger_2=linalg.pinv2(A)
A_dagger_2

### 4.10 求解特征值和特征矢量问题

#### 特征值问题

$$\boldsymbol{A}\boldsymbol{v} = \lambda\boldsymbol{v}$$

#### 特征方程

$$\left|\boldsymbol{A}-\lambda\boldsymbol{I}\right| = 0$$

#### 考虑

$$
A=
\left[
\begin{array}{ccc}
1 & 5 & 2 \\
2 & 4 & 1 \\
3 & 6 & 2
\end{array}
\right]
$$

#### 其特征值为

$$
\left\{
\begin{array}{rcr}
\lambda_1 & = & 7.9579 \\
\lambda_2 & = & -1.2577 \\
\lambda_3 & = & 0.2997
\end{array}
\right.
$$

In [ ]:
A = np.array([[1, 5, 2], [2, 4, 1], [3, 6, 2]])
la, v = linalg.eig(A)
l1, l2, l3 = la
print(l1, l2, l3) # 特征值

In [ ]:
print(v[:, 0]) # 第一个特征矢量

In [ ]:
print(v[:, 1])  # 第二个特征矢量

In [ ]:
print(v[:, 2])  # 第三个特征矢量

In [ ]:
print(np.sum(abs(v**2), axis=0)) # 单位矢量

In [ ]:
v1 = np.array(v[:, 0]).T
print(linalg.norm(A.dot(v1) - l1*v1)) # 检查

### 4.11 奇异值分解

- 奇异值分解可看着是特征值问题的推广
- 设 $\boldsymbol{A}$ 是一 $M\times N$ 矩阵
- 于是，矩阵 $\boldsymbol{A}^H\boldsymbol{A}$ 和 $\boldsymbol{A}\boldsymbol{A}^H$ 是半正定共轭方阵
- 由线代理论，必有非负实特征值若干，记为 $\sigma_i^2$，它们的平方根就称为矩阵 $\boldsymbol{A}$ 的奇异值
- 相应地，有以下分解形式

$$\boldsymbol{A} = \boldsymbol{U}\boldsymbol{\Sigma}\boldsymbol{V}^H$$

- 即为奇异值分解。
- 其中
    - $\boldsymbol{U}$ 和 $\boldsymbol{V}$ 是酉矩阵
    - $\boldsymbol{\Sigma}$ 是奇异值构成的对角阵
- 求奇异值分解的 scipy 命令为 

```python
>>> linalg.diagsvd
```

#### 例如

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A

In [ ]:
M,N = A.shape
U,s,Vh = linalg.svd(A)
Sig = linalg.diagsvd(s,M,N)
U, Vh = U, Vh
U

In [ ]:
Sig

In [ ]:
Vh

In [ ]:
U.dot(Sig.dot(Vh)) # 检查

### 4.12 矩阵的各种分解法

- QR 分解
- LU 分解
- LDLT 分解
- Cholesky 分解
- Schur 分解

参考在线文档 [scipy.linalg](http://docs.scipy.org/doc/scipy/reference/linalg.html#scipy.linalg)

#### LU 分解示例

In [ ]:
A=sp.mat('[1 2 3;0 1 2;2 4 1]')
A

In [ ]:
x, y, z=linalg.lu(A)

In [ ]:
x

In [ ]:
y

In [ ]:
z

#### Cholesky 分解示例

In [ ]:
A = np.array([[1,-2j],[2j,5]])
L = linalg.cholesky(A, lower=True)
L

In [ ]:
sp.dot(L, L.T.conj())

#### Schur 分解示例

In [ ]:
A = np.mat('[1 3 2; 1 4 5; 2 3 6]')
T, Z = linalg.schur(A)
T1, Z1 = linalg.schur(A, 'complex')
T2, Z2 = linalg.rsf2csf(T, Z)
T

In [ ]:
T2

In [ ]:
abs(T1 - T2) # different

In [ ]:
abs(Z1 - Z2) # different

In [ ]:
T, Z, T1, Z1, T2, Z2 = map(np.mat,(T,Z,T1,Z1,T2,Z2))
abs(A - Z*T*Z.H) # same

In [ ]:
abs(A - Z1*T1*Z1.H) # same

In [ ]:
abs(A - Z2*T2*Z2.H) # same

### 4.13 特殊矩阵

| 类型 | 函数 | 说明 |
|-------|-------|-------|
| block diagonal | scipy.linalg.block_diag | 创建分块对角矩阵 |
| circulant | scipy.linalg.circulant | 创建 circulant 阵 |
| companion | scipy.linalg.companion | 创建 companion 阵 |
| Hadamard | scipy.linalg.hadamard | 创建 Hadamard 阵 |
| Hankel | scipy.linalg.hankel | 创建 Hankel 阵 |
| Hilbert | scipy.linalg.hilbert | 创建 Hilbert 阵 |
| Inverse Hilbert | scipy.linalg.invhilbert| 创建逆 Hilbert 阵 |
| Leslie | scipy.linalg.leslie | 创建 Leslie 阵 |
| Pascal | scipy.linalg.pascal | 创建 Pascal 阵 |
| Toeplitz | scipy.linalg.toeplitz | 创建 Toeplitz 阵 |
| Van der Monde | numpy.vander | 创建 Van der Monde 阵 |

### 结束